### ISSUE TITLE
Desired Actions after contributing are unclear

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/tech-dapp#140] opened 2021-01-26 02:58 UTC
Some CTAs after making a contribution (besides Tweeting/TG) would kill it. Maybe under the benefits. Otherwise, it feels like an orphan space with no desired actions and no reason to come back to.

**Comment by tamarandom** [comment] 2021-02-02 15:16
Hey @knobsdao What are you thinking about in terms of the CTA!? Join us on discord!? Let's get specific so we can execute it.

**Comment by knobsdao** [comment] 2021-02-08 17:13
Hey @knobsdao What are you thinking about in terms of the CTA!? Join us on discord!? Let's get specific so we can execute.

Depends on strategy. A dedicated Discord channel may be the best option. Pinning @krisjpi.

**Comment by tamarandom** [comment] 2021-02-10 19:48
Dupe of #104

**Closed by tamarandom** 2021-02-10 19:48 UTC
Labels: Nice to have
