### ISSUE TITLE
Remove alpha channel on all text and fix DAI logo

### ISSUE THREAD

**Issue by markoprljic** [commons-stack/tech-dapp#122] opened 2021-01-16 12:42 UTC
Why is this DAI logo color so dark? The text css has an alpha channel on it. 
Remove the alpha channel on all text and thus make the DAI logo shine again :)

**Comment by tamarandom** [comment] 2021-02-02 14:24
@markoprljic @sponnet I'm tagging this Nice to Have unless you think it needs a higher priority!? Hard to visualize that the issue is by the description alone.

**Comment by markoprljic** [comment] 2021-02-02 15:23
Is this already done? @sponnet

**Comment by markoprljic** [comment] 2021-02-02 15:24
Yes I see @sponnet committed the code related to this issue so we can close this one @tamarandom

**Comment by tamarandom** [comment] 2021-02-02 16:40
Awesome! Closing.

**Closed by tamarandom** 2021-02-02 16:40 UTC
Labels: Nice to have
