### ISSUE TITLE
Tweet and telegram sharing suggestion 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/tech-dapp#135] opened 2021-01-26 00:23 UTC
"I funded CS" doesn't want to make me share it. 🙈
Let's make a meme!!!

**Comment by tamarandom** [comment] 2021-02-02 15:12
You have a point, @liviade1 !
@krisjpi Can you chip in with a compelling message that can replace the placeholder please please!?

**Comment by tamarandom** [comment] 2021-02-10 19:47
Dupe of #104

**Closed by tamarandom** 2021-02-10 19:47 UTC
Labels: Nice to have
